parameters:
  - name: projectName
    type: string
  - name: BuildConfiguration
    type: string
  - name: deploy
    type: string
  - name: PreProdSpecificVariableGroup
    type: string
    default: ''

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - template: ../job/code-build.yml
        parameters:
          BuildConfiguration: ${{ parameters.BuildConfiguration }}
          projectName: ${{ parameters.projectName }}

  - stage: Deploy_TEST
    dependsOn: Build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'Schedule'))
    displayName: Deploy to TEST
    variables:
      - group: "TEST DevTest Shared Resources"
      - group: "TEST Automation Suite Variables"
    jobs:
      - template: ../job/deploy.yml
        parameters:
          Environment: TEST
          ServiceConnection: das-test-automation-test-suite-db-sc

  - stage: Deploy_TEST2
    dependsOn: Build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'Schedule'))
    displayName: Deploy to TEST2
    variables:
      - group: "TEST2 DevTest Shared Resources"
      - group: "TEST2 Automation Suite Variables"
    jobs:
      - template: ../job/deploy.yml
        parameters:
          Environment: TEST2
          ServiceConnection: das-test2-automation-test-suite-db-sc

  - stage: Deploy_DEMO
    dependsOn: Build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'Schedule'))
    displayName: Deploy to DEMO
    variables:
      - group: "DEMO DevTest Shared Resources"
      - group: "DEMO Automation Suite Variables"
    jobs:
      - template: ../job/deploy.yml
        parameters:
          Environment: DEMO
          ServiceConnection: das-demo-automation-test-suite-db-sc

  - stage: Deploy_PP
    dependsOn: Build
    displayName: Deploy to PP
    variables:
      - group: "PreProd Management Resources"
      - group: "PreProd Shared Resources"
      - group: "PreProd Automation Suite Variables"
      - ${{ if ne(parameters.PreProdSpecificVariableGroup, '') }}:
        - group: ${{ parameters.PreProdSpecificVariableGroup }}
    jobs:
      - template: ${{ if eq(variables['Build.Reason'], 'Schedule') then '../job/deploy.yml' else (if ne(variables['ResourceName'], '') then '../job/api-deploy.yml' else '../job/deploy.yml') }}
        parameters:
          Environment: ${{ if eq(variables['Build.Reason'], 'Schedule') then 'PP_AUTOMATION' else 'PP' }}
          ServiceConnection: das-pp-automation-test-suite-db-sc
