trigger: none
pr: none
schedules:
- cron: '30 3 * * 1-5'
  displayName: ScheduledRun
  branches:
    include:
    - master
  always: true

variables:
  - template: ../pipeline-templates/vars.yml
  - name: projectName
    value: "SFA.DAS.Digicerts.UITests"

resources:
  repositories:
    - repository: self
    - repository: das-platform-building-blocks
      type: github
      name: SkillsFundingAgency/das-platform-building-blocks
      ref: refs/tags/3.0.17
      endpoint: SkillsFundingAgency
    - repository: das-platform-automation
      type: github
      name: SkillsFundingAgency/das-platform-automation
      ref: refs/tags/5.1.17
      endpoint: SkillsFundingAgency

pool:
  vmImage: 'windows-latest'

stages:
  - template: ../pipeline-templates/stage/environment-stage.yml
    parameters:
      projectName: $(projectName)
      BuildConfiguration: $(BuildConfiguration)
      deploy: $(Deploy)

 -  stage: Deploy_AT
    dependsOn: Build
    displayName: Deploy to AT
    condition: and(succeeded(), eq(variables.Deploy, 'true'))
    variables:
      - group: DevTest Management Resources
      - group: AT DevTest Shared Resources
      - group: AT das-apprentice-app
    jobs:
      - template: ../job/deploy.yml
        parameters:
          Environment: AT
          ServiceConnection: das-at-automation-test-suite-db-sc
          ResourceName: ${{ parameters.ResourceName }}
          RuleName: ${{ parameters.RuleName }}

 -  stage: Deploy_TEST
    dependsOn: Build
    condition: succeeded()
    displayName: Deploy to TEST
    variables:
      - group: "DevTest Management Resources"
      - group: "TEST DevTest Shared Resources"
      - group: "TEST Automation Suite Variables"
    jobs:
      - template: ../job/deploy.yml
        parameters:
          Environment: TEST
          ServiceConnection: das-test-automation-test-suite-db-sc
          ResourceName: ${{ parameters.ResourceName }}
          RuleName: ${{ parameters.RuleName }}

  - stage: Deploy_TEST2
    dependsOn: Build
    condition: succeeded()
    displayName: Deploy to TEST2
    variables:
      - group: "TEST2 Management Resources"
      - group: "TEST2 DevTest Shared Resources"
      - group: "TEST2 Automation Suite Variables"
    jobs:
      - template: ../job/deploy.yml
        parameters:
          Environment: TEST2
          ServiceConnection: das-test2-automation-test-suite-db-sc
          ResourceName: ${{ parameters.ResourceName }}
          RuleName: ${{ parameters.RuleName }}

  - stage: Deploy_DEMO
    dependsOn: Build
    condition: succeeded()
    displayName: Deploy to DEMO
    variables:
      - group: "DEMO Management Resources"
      - group: "DEMO DevTest Shared Resources"
      - group: "DEMO Automation Suite Variables"
    jobs:
      - template: ../job/deploy.yml
        parameters:
          Environment: DEMO
          ServiceConnection: das-demo-automation-test-suite-db-sc
          ResourceName: ${{ parameters.ResourceName }}
          RuleName: ${{ parameters.RuleName }}

  - stage: Deploy_PP
    dependsOn: Build
    displayName: Deploy to PP
    variables:
      - group: "PreProd Management Resources"
      - group: "PreProd Shared Resources"
      - group: "PreProd Automation Suite Variables"
      - ${{ if ne(parameters.PreProdSpecificVariableGroup, '') }}:
        - group: ${{ parameters.PreProdSpecificVariableGroup }}

    jobs:
      - ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
        - template: ../job/deploy.yml
          parameters:
            Environment: 'PP_AUTOMATION'
            ServiceConnection: das-pp-automation-test-suite-db-sc
            RuleName: ${{ parameters.RuleName }}
            ResourceName: ${{ parameters.ResourceName }}
            WhiteListFunction: ${{ parameters.WhiteListFunction }}

      - ${{ else }}:
        - template: ../job/deploy.yml
          parameters:
            Environment: 'PP'
            ServiceConnection: das-pp-automation-test-suite-db-sc
            ResourceName: ${{ parameters.ResourceName }}
            RuleName: ${{ parameters.RuleName }}
            WhiteListFunction: ${{ parameters.WhiteListFunction }}