Feature: EMPACC_API_10_SearchOrganisationOrganisationsResults

@api
@employeraccountsapiResourceNotavailable
@outerapi
@regression
Scenario: EMPACC_API_10_SearchOrganisationOrganisationsResults
#	Then endpoint /SearchOrganisation/organisations/search/results can be accessed