using SFA.DAS.ApprenticeCMAD.UITests.Project.Helpers;
using SFA.DAS.ApprenticeCMAD.UITests.Project.Pages;
using SFA.DAS.Login.Service.Project.Helpers;
using Microsoft.Playwright;
using Reqnroll;

namespace SFA.DAS.ApprenticeCMAD.UITests.Project.StepDefinitions
{
    [Binding]
    public class CmadLoginStepDefinitions(ScenarioContext context)
    {
        private readonly CmadStepsHelper _cmadSteps = new(context);

        [When(@"the apprentice logs into the CMAD application via the developer stub page")]
        public async Task WhenTheApprenticeLogsIntoTheCMADApplicationViaTheDeveloperStubPage()
        {
            // 1. Direct browser instance to the unique CMAD portal URL
            await _cmadSteps.NavigateToCmadStubSignInAsync();

            // 2. Fetch the dynamic profile parameters generated by your core database hooks
            var activeUser = context.Get<AppCMADUser>();

            // 3. Authenticate using the authentic CMAD BasePage wrapper subclass
            var cmadSignInPage = new CmadStubSignInPage(context);
            await cmadSignInPage.SignInAsync(activeUser.IdOrUserRef, activeUser.Username);

            // 4. Stand down execution until the core portal shell stabilizes
            await _cmadSteps.Page.WaitForLoadStateAsync(LoadState.DOMContentLoaded);
        }

        [Then(@"the apprentice is taken to the CMAD home view dashboard")]
        public async Task ThenTheApprenticeIsTakenToTheCMADHomeViewDashboard()
        {
            await Assertions.Expect(_cmadSteps.Page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex(".*/home|.*/dashboard"));
        }

        [Then(@"the apprentice should see their approved employment details correctly populated")]
        public async Task ThenTheApprenticeShouldSeeTheirApprovedEmploymentDetailsCorrectlyPopulated()
        {
            var activeUser = context.Get<AppCMADUser>();
            // Perform explicit assertions against your isolated CMAD elements here...
            await Task.CompletedTask;
        }
    }
}