parameters:
  - name: ServiceConnection
    type: string
  - name: Environment
    type: string

jobs:
- deployment: Deploy_AutomationTests
  displayName: 'Deploy Automation Tests to ${{ parameters.Environment }}'
  environment: ${{ parameters.Environment }}
  pool:
    vmImage: 'windows-latest'
  strategy:
    runOnce:
      deploy:
        steps:
          - task: ExtractFiles@1
            displayName: 'Extract files'
            inputs:
              archiveFilePatterns: '**/tests.zip'
              destinationFolder: '$(System.DefaultWorkingDirectory)/das-playwright-automation-test-suite/drop/tests'

          - task: TotalALM.totalalm-tokenization.tokenization-build-task.Tokenization@2
            displayName: 'Tokenization: Transform file *.json'
            inputs:
              SourcePath: '$(System.DefaultWorkingDirectory)/das-playwright-automation-test-suite/drop/tests'
              TargetFileNames: '*.json'

          - task: PowerShell@2
            displayName: 'Update NumberOfTestWorkers'
            inputs:
              targetType: filePath
              filePath: '$(System.DefaultWorkingDirectory)/das-playwright-automation-test-suite/drop/tests/src/UpdateNoofTestWorkers.ps1'
              arguments: '-browser $(BROWSER_TYPE)'

          - task: TotalALM.totalalm-tokenization.tokenization-build-task.Tokenization@2
            displayName: 'Tokenization: Transform file *.runsettings'
            inputs:
              SourcePath: '$(System.DefaultWorkingDirectory)/das-playwright-automation-test-suite/drop/tests/runsettings/src/'
              TargetFileNames: '*.runsettings'

          - task: PowerShell@2
            displayName: 'Install Playwright Browsers'
            inputs:
              targetType: filePath
              filePath: '$(System.DefaultWorkingDirectory)/das-playwright-automation-test-suite/drop/tests/SFA.DAS.Campaigns.UITests/playwright.ps1'
              arguments: install

          - task: ms-autotest.screen-resolution-utility-task.screen-resolution-utlity-task.ScreenResolutionUtility@1
            displayName: 'Set Screen Resolution'
            inputs:
              displaySettings: specific
              width: 1920
              height: 1080

          - task: AzurePowerShell@5
            displayName: "Get Agent's IP Address"
            inputs:
              azureSubscription: ${{ parameters.ServiceConnection }}
              ScriptPath: '$(System.DefaultWorkingDirectory)/das-platform-automation/Infrastructure-Scripts/Get-MyIpAddress.ps1'
              ScriptArguments: '-WhatsMyIpUrl "https://ifconfig.me/ip"'
              azurePowerShellVersion: LatestVersion

          - task: AzurePowerShell@5
            displayName: "Whitelist agent's IP address"
            inputs:
              azureSubscription: ${{ parameters.ServiceConnection }}
              ScriptPath: '$(System.DefaultWorkingDirectory)/das-platform-automation/Infrastructure-Scripts/Add-AzSqlIpException.ps1'
              ScriptArguments: '-Name $(Build.DefinitionName) -IPAddress $(IPAddress) -ResourceNamePattern $(SharedSQLServerName)'
              azurePowerShellVersion: LatestVersion

          - task: VSTest@2
            displayName: 'VsTest - Test Execution '
            inputs:
              testAssemblyVer2: '**\SFA.DAS.EarlyConnectForms.UITests\SFA.DAS.EarlyConnectForms.UITests.dll'
              searchFolder: '$(System.DefaultWorkingDirectory)/das-playwright-automation-test-suite/drop/tests/'
              testFiltercriteria: '"$(TestCategory)&TestCategory!=ignoreinpp&TestCategory!=accessibility"'
              runSettingsFile: '$(System.DefaultWorkingDirectory)/das-playwright-automation-test-suite/drop/tests/runsettings/src/Parellel.runsettings'
              runInParallel: true
              otherConsoleOptions: '/logger:trx'
              rerunFailedTests: true
              rerunType: basedOnTestFailureCount
              rerunMaxAttempts: 2
            continueOnError: true

          - task: AzurePowerShell@5
            displayName: "SQL - Remove Whitelisted Agent's IP Address"
            inputs:
              azureSubscription: ${{ parameters.ServiceConnection }}
              ScriptPath: '$(System.DefaultWorkingDirectory)/das-platform-automation/Infrastructure-Scripts/Remove-AzSqlIpException.ps1'
              ScriptArguments: '-Name $(Build.DefinitionName) -IPAddress $(IPAddress) -ResourceNamePattern $(SharedSQLServerName)'
              azurePowerShellVersion: LatestVersion
            condition: succeededOrFailed()

          - task: PowerShell@2
            displayName: 'Check .trx File Exists'
            inputs:
              targetType: filePath
              filePath: '$(System.DefaultWorkingDirectory)/das-playwright-automation-test-suite/drop/tests/src/Check-TestResults.ps1'
              arguments: '-SourcePath "$(Agent.TempDirectory)/TestResults"'
