trigger:
  batch: true
  branches:
    include:
      - master

variables:
  - name: BuildConfiguration
    value: release
  - name: BuildPlatform
    value: any cpu
  - group: "Release Automation Suite Variables"
  - group: "Release Automation Suite Variables (Db)"
  - group: "Provider Release Automation Suite Variables"
  - group: "RELEASE APP_das-p-earlyconnect-forms"
  - name: Deploy
    value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))]

resources:
  repositories:
    - repository: self
    - repository: das-platform-building-blocks
      type: github
      name: SkillsFundingAgency/das-platform-building-blocks
      ref: refs/tags/3.0.10
      endpoint: SkillsFundingAgency
    - repository: das-platform-automation
      type: github
      name: SkillsFundingAgency/das-platform-automation
      ref: refs/tags/5.1.8
      endpoint: SkillsFundingAgency

stages:
  - stage: Build
    jobs:
      - template: pipeline-templates/job/code-build.yml

  - stage: Deploy_TEST
    dependsOn: Build
    displayName: Deploy to TEST
    variables:
      - group: "PreProd Management Resources"
      - group: "PreProd Shared Resources"
      - group: "PreProd Automation Suite Variables"
      - group: "TEST APP_das-p-earlyconnect-forms"
    jobs:
      - template: pipeline-templates/job/deploy.yml
        parameters:
          Environment: TEST
          ServiceConnection: SFA-DIG-PreProd-ARM


  - stage: Deploy_PP
    dependsOn: Build
    displayName: Deploy to PP
    variables:
      - group: "PreProd Management Resources"
      - group: "PreProd Shared Resources"
      - group: "PreProd Automation Suite Variables"
      - group: "PREPROD das-accessibility-automation-test-suite"
    jobs:
      - template: pipeline-templates/job/deploy.yml
        parameters:
          Environment: PP
          ServiceConnection: SFA-DIG-PreProd-ARM
