trigger:
  batch: true
  branches:
    include:
      - "*"

variables:
  buildConfiguration: 'release'

resources:
  repositories:
    - repository: das-platform-building-blocks
      type: github
      name: SkillsFundingAgency/das-platform-building-blocks
      ref: refs/tags/2.1.28
      endpoint: SkillsFundingAgency
    - repository: das-platform-automation
      type: github
      name: SkillsFundingAgency/das-platform-automation
      ref: refs/tags/5.1.17
pool:
  vmImage: 'windows-latest'

jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      BuildConfiguration: $(buildConfiguration)
