trigger: none
pr: none
schedules:
- cron: '0 2 * * 1-5'
  displayName: ScheduledRun
  branches:
    include:
    - master
  always: true

variables:
  - name: BuildConfiguration
    value: release
  - name: BuildPlatform
    value: any cpu
  - group: "Release Automation Suite Variables"
  - group: "Release Automation Suite Variables (Db)"
  - group: "Provider Release Automation Suite Variables"
  - group: "RELEASE APP_as-GAA"
  - name: Deploy
    value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))]
  - name: projectName
    value: "SFA.DAS.EarlyConnectForms.UITests"
  - name: PreProdSpecificVariableGroup
    value: "PREPROD APP_as-GAA"

resources:
  repositories:
    - repository: self
    - repository: das-platform-building-blocks
      type: github
      name: SkillsFundingAgency/das-platform-building-blocks
      ref: refs/tags/2.1.28
      endpoint: SkillsFundingAgency
    - repository: das-platform-automation
      type: github
      name: SkillsFundingAgency/das-platform-automation
      ref: refs/tags/5.1.17
      endpoint: SkillsFundingAgency

pool:
  vmImage: 'windows-latest'

stages:
  - template: ../pipeline-templates/stage/enviroment-stage.yml
    parameters:
      projectName: $(projectName)
      BuildConfiguration: $(BuildConfiguration)
      deploy: $(Deploy)
